### ISSUE TITLE
Dealing cleanly with etckeeper commits generated on-server

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/hashbang#10]
It's high-time we got a cleaner solution for dealing with `etckeeper` commits generated on-server:
- The current setup is very annoying to deal with when a package upgrade causes all servers to produce a commit during a `shell.yml` Ansible run.
- This is blocking for https://github.com/hashbang/admin-tools/issues/21

The proposed solution is as follows:
- [x] deploy a simple Git repo with per-branch permissions (gitolite does that nicely);
- [x] give each server an SSH key (accessible only by root) and give it push access to a dedicated branch;
- [ ] [make the server actually push to that dedicated branch](https://github.com/hashbang/shell-etc/pull/106);
- [ ] add a Git hook (on the gitolite side) to email us (and/or notify on IRC) when changes are pushed.

The workflow is described in https://github.com/hashbang/shell-etc/pull/106

Pros:
- We get for free an up-to-date, versioned description of what is currently deployed on each server.
- This is easy to adapt if/when we decide to have a testing branch, a server (or more!) running that branch and the others pulling from a more stable branch:
  - add the testing branch on Github and make the canary server pull from it;
  - merge canary-server commits back into the testing branch;
  - once something is tested, merge it into master.

**Comment by KellerFuchs** [comment]
@ChickenNuggers @daurnimator @lrvick @hashbang/administrators Thoughts about this?

**Comment by daurnimator** [comment]
sounds reasonable and secure. 

though its not as simple/convinient; nor will anyone stand without reading the docs. Makes me hesitant.

**Comment by KellerFuchs** [comment]
@daurnimator Well, the situation right now involves having to ssh to boxes, inspect the diff with `origin/master` and `etckeeper vcs reset --hard origin/master` if appropriate, whenever the automation fail.

I agree it's not as good as the “ideal” “stuff gets pushed” situation, but:
- I'm not sure it's even possible to do it safely:
  think “`shell.yml` runs, a bunch of pkg upgrades create `/etc` changes, every server commits independently”;
- that runs contrary to what you wanted a while back:
  you stated that giving `root` push access, through an admin's SSH agent or not, is dirty.

Regarding the documentation, well, it's really something that only concerns us admins; we can reasonably assume admins either know the setup or can be bothered to read the doc (esp. if there is a link in the mail notification).

However, I would be very happy if you can see a way to make it simpler.

**Comment by KellerFuchs** [comment]
@daurnimator Also, I would be interested in knowing in which ways it's not as simple/convenient as the current situation for your workflow:

> But also, I don't have ssh agent turned on. I pull to a local dir, then push from there.

You just replace the “pull to a local dir” by “pull from servers/foo”, which can even be done from anywhere (rather than locally).

**Comment by lrvick** [comment]
@KellerFuchs can you update the workflow above to detail how this flow will work -without- changes being made directly on-server? (e.g with local docker or vagrant shell-server  that modifies a local checkout of shell-etc as discussed in other issues)

**Comment by KellerFuchs** [comment]
@lrvick The workflow is described in https://github.com/hashbang/shell-etc/pull/106
