### ISSUE TITLE
HTTPSify outward-facing services with Letsencrypt

### ISSUE THREAD

**Issue by erinzm** [hashbang/hashbang#2]
@lrvick, @KellerFuchs, and I have talked about possible methods for doing this.
The major issue is https access for site verification; a custom nginx proxy is one idea, and @lrvick had another which I've forgotten.

This issue serves as a general purpose discussion forum to discuss implementation.

**Comment by KellerFuchs** [comment]
@ArchimedesPi Which services?  Do you mean user homepages?  (Those aren't even cleanly reachable yet)

**Comment by erinzm** [comment]
@KellerFuchs anything that we can slap SSL on, so hashbang.sh and irc right now.

**Comment by RyanSquared** [comment]
If that's the only two things that we can slap TLS (not SSL, TLS. >_>) on, then we've got issues. :P

**Comment by KellerFuchs** [comment]
@ArchimedesPi `hashbang.sh` and the IRC servers already use TLS.
Also, LE won't issue certificates for `hashbang.sh` (subdomains are fine), given that it is in the public suffix list.

**Comment by KellerFuchs** [comment]
@ArchimedesPi I don't get whether that answers your initial issue.
If it does, please close the issue, and if not please clarify.

**Comment by erinzm** [comment]
Ehh, nvm, I'll close this, we'll talk about it on IRC later. I'm not sure I
remember all the specifics.

Liam Marshall
