### ISSUE TITLE
SSL Certificate Expired for hashbang.sh

### ISSUE THREAD

**Issue by gmcclins** [hashbang/hashbang#21]
There are issues with the sites certificate chain (net::ERR_CERT_DATE_INVALID).

Valid from 10/3/15 to 10/3/16

**Comment by KellerFuchs** [comment]
@gmcclins Thanks for the report.
More worryingly, the cert is also user for LDAP, IRC and the mail server.

I already started the renewal process with GlobalSign ~8 hours ago.

**Comment by KellerFuchs** [comment]
Oops, we forgot to close this.
