### ISSUE TITLE
Journald does not save messages, is not accessible through commands.

### ISSUE THREAD

**Issue by NotAFile** [hashbang/hashbang#22]
I used to be able to send my script logs to journald and have that work fine, but after ny1 went back up, this is no longer possible.

```
$ journalctl
No journal files were found
$ journalctl --user
No journal files were found
$ systemctl --user status unitfile
● unitname.service - UnitName
   Loaded: loaded (/home/username/.config/systemd/user/unitname.service; enabled)
   Active: active (running) since Mi 2017-02-08 18:30:11 UTC; 2min 24s ago
 Main PID: 24011 (sh)
   CGroup: /user.slice/user-[numbers].slice/user@[numbers].service/unitname.service
           ├─24011 /bin/sh -c /home/username/foldername/env/bin/python main.py
           └─24012 /home/username/foldername/env/bin/python main.py
```

(notable here is the lack of logs in `systemctl status`, which normally prints the most recent logs of the unit.

**Comment by KellerFuchs** [comment]
Note: problem only occurs on `ny1`

**Comment by daurnimator** [comment]
I think this is caused by permissions on /etc/machine-id:

`open("/etc/machine-id", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)`

**Comment by daurnimator** [comment]
I manually set the permissions on /etc/machine-id and `journalctl --user` started working again.
As this was only an issue on ny1 I'm going to assume this was not an issue with shell-etc and instead a result of the last recovery process.

**Comment by NotAFile** [comment]
Thanks!

**Comment by KellerFuchs** [comment]
@daurnimator Thanks for debugging this.
