### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by CodeMaxx** [hashbang/hashbang#31]
Hi, I just came across the hashbang network. Is the network still active? I'm asking because `gpg` wasn't able to verify the signature on `gpg --verify <(curl https://hashbang.sh)`

**Comment by RyanSquared** [comment]
Yes, we're still active. What was the exact error? Did you import our keys into your system before verifying?

**Comment by CodeMaxx** [comment]
`gpg --recv-keys 0xD2C4C74D8FAA96F5` gave me `gpg: keyserver receive failed: No route to host`

**Comment by KellerFuchs** [comment]
@CodeMaxx Sounds like you either didn't have network access at that point or have a GnuPG configuration issue.
Try `gpg --keyserver keys.gnupg.net --recv-keys 0xD2C4C74D8FAA96F5` ?

**Comment by CodeMaxx** [comment]
This gives me the same error. Probably a configuration issue.

**Comment by CodeMaxx** [comment]
Ok so this finally worked.
`gpg --keyserver keyserver.ubuntu.com --recv-keys 0xD2C4C74D8FAA96F5` 

I also get this though
```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```
on `curl https://hashbang.sh | gpg -o hashbang.sh`

**Comment by KellerFuchs** [comment]
OK, this confirms this was a GnuPG issue on your side.

“This key is not certified with a trusted signature” is expected: you probably do not have a trust-chain to `0xD2C4C74D8FAA96F5`.

**Comment by CodeMaxx** [comment]
Yeah my web of trust is small
