### ISSUE TITLE
Synchronize the “administrators” list

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/hashbang#8]
Currently, the list of administrators is present in 3 places:
- the LDAP group `sudo`;
- Ansible's [user data](https://github.com/hashbang/admin-tools/blob/master/group_vars/all);
- the Github [“Administrators” team](https://github.com/orgs/hashbang/teams/administrators);
- the pass db's [keys list](https://github.com/hashbang/password-store/blob/master/.gpg-id).

I suggest we resync them (by hand, as appropriate) and make the Github team public (the other lists are public anyhow, except for the pass db).

Here are the impacted users:
- [x] @deleriux2 (dropped by timeout)
- [x] @scjudd (dropped by timeout)
- [x] @SaidinWoT (dropped by request)
- [x] @theepicsnail (dropped by request)
- [x] @notnamed (dropped by request)
- [x] radicalcakes a.k.a. @thenormalsquid (dropped by request)
- [x] @tsoporan (dropped by request)
- [x] cbrooks a.k.a. @connerbrooks (has all needed access)
- [x] viaken a.k.a. @dpflug (has all needed access)
- [ ] gscott, aka @picardrulez  (only exists [in Ansible](https://github.com/hashbang/admin-tools/pull/33))

~~I took the liberty of removing notnamed, tsoporan and radicalcakes from the group `sudo`, since there is no way to contact them (not on Github or IRC).~~

_NOTE_: What I'm suggesting here is a one-off, manual thing.  No automation at all,

**Comment by KellerFuchs** [comment]
I think we should do that because:
- there should be a clear set of people who have admin access to the infrastructure;
- people who are in one of those lists but not all (for historical reasons) are _de facto_ prevented from contributing, and should have all the access needed (if they still wish to contribute);
- this makes the whole situation more transparent for users.

I think it should not be automated because:
- the set of admins changes infrequently;
- the process for adding a new admin is already documented;
- automation failure can have catastrophic consequences there.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Follow-up from the discussion in `#opers`, since it devolved in fairly unrelated directions.

**Comment by RyanSquared** [comment]
> NOTE: What I'm suggesting here is a one-off, manual thing. No automation at all.

I approve, then.

**Comment by KellerFuchs** [comment]
So, those people aren't in Ansible or in the Github team:
- [ ] @deleriux2 (not in Ansible)
- [x] radicalcakes (not in Ansible nor Github)
- [ ] viaken (neither in Ansible nor in Github)
- [ ] @theepicsnail (not in Ansible)
- [x] notnamed (not in Ansible nor in Github)
- [ ] cbrooks (not in Ansible nor Github)
- [x] tsoporan (not in Ansible nor Github)
- [ ] gscott (not in Ansible nor Github)
- [ ] @dpflug (not in Ansible nor LDAP)
- [ ] @scjudd (not in Ansible nor LDAP)

I took the liberty of removing notnamed, tsoporan and radicalcakes from the group `sudo`, since there is no way to contact them (not on Github or IRC).

**Comment by daurnimator** [comment]
> I took the liberty of removing notnamed, tsoporan and radicalcakes from the group sudo, since there is no way to contact them (not on Github or IRC).

Huh? why can't we contact @tsoporan?

**Comment by KellerFuchs** [comment]
@daurnimator It wasn't autocompleting, so I assumed it was non-existing  :-(

**Comment by KellerFuchs** [comment]
@daurnimator Do you know if notnamed was @notnamed?

**Comment by notnamed** [comment]
Hello yes that notnamed is this notnamed, but you can feel free to sync me out of sudo, Ansible, and Github.

**Comment by KellerFuchs** [comment]
@notnamed Ok, thanks for the confirmation.

**Comment by SaidinWoT** [comment]
I should be on this list. I believe.

**Comment by KellerFuchs** [comment]
@SaidinWoT You already had a pending invite to the “administrators” group on Github.
You can send a PR against [admin-tools](https://github.com/hashbang/admin-tools/blob/master/group_vars/all) to add yourself there, and you need to tell me what is your shell user, to add it to the `sudo` group.

**Comment by thenormalsquid** [comment]
I should be on this list. I believe. I am radicalcakes.

**Comment by KellerFuchs** [comment]
@thenormalsquid  Same punishment as @SaidinWoT : PR to admin-tools  :grin:

We should definitely keep /somewhere/ the mapping from shell name to Github username (and IRC nick?)

**Comment by KellerFuchs** [comment]
@connerbrooks @dpflug Just realised you are missing in the password store too.
Add your key to [the list](https://github.com/hashbang/password-store/blob/master/.gpg-id) (preferably with a signed commit) and I will re-encrypt the pass db.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Do you think we should set a cut-off date where we remove privileges from people who haven't answered whether they want to keep being part of the admin team?

**Comment by RyanSquared** [comment]
Until the end of May seems fine.

**Comment by KellerFuchs** [comment]
@ChickenNuggers ACK.  Fine for me

**Comment by KellerFuchs** [comment]
@deleriux2 @scjudd Ping?

**Comment by KellerFuchs** [comment]
Wheeee, 50% done.

Still haven't heard of @deleriux2, @tsoporan or @scjudd 
Will prod gscott and @SaidinWoT with a sharp stick.

**Comment by picardrulez** [comment]
I'm still down.

**Comment by tsoporan** [comment]
Feel free to remove me from the list.

**Comment by KellerFuchs** [comment]
@tsoporan Thanks for the notice.

**Comment by KellerFuchs** [comment]
Dun dun dun.
Since we didn't hear from @deleriux2 and @scjudd before reaching the end of the month, I will just go ahead and remove accesses.

**Comment by KellerFuchs** [comment]
@SaidinWoT @picardrulez Go, go!

**Comment by KellerFuchs** [comment]
@picardrulez @SaidinWoT I would be sad to see the snail race end, but it have been half-a-month _past_ the deadline.

**Comment by theepicsnail** [comment]
Snail race is best race.

**Comment by KellerFuchs** [comment]
@theepicsnail Snail master race, right?

**Comment by KellerFuchs** [comment]
Congratulations, @picardrulez, you won the snail race!
It would still be pretty cool if you could send the info so that we can add you to the pass db.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Given that picardrulez/gscott is timeout-ing hard, I just dropped his access.

Closing the issue under the assumption that https://github.com/hashbang/admin-tools/issues/33 will be merged.
